-- ============================================================
--  길드전 작전상황실 — Supabase 테이블 생성 SQL
--  Supabase 대시보드 > SQL Editor 에서 전체 실행
-- ============================================================

-- 1. 멤버 테이블 (닉네임 + 비밀번호키 + 권한 + 상태)
CREATE TABLE IF NOT EXISTS members (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nick           TEXT NOT NULL,
    key            TEXT NOT NULL,
    role           TEXT NOT NULL DEFAULT 'user',     -- 'admin' | 'user'
    status         TEXT NOT NULL DEFAULT 'pending',  -- 'active' | 'pending' | 'rejected'
    must_change_pw BOOLEAN NOT NULL DEFAULT false
);

-- 기존 members 테이블에 컬럼 추가 (이미 테이블이 있는 경우 실행)
-- ALTER TABLE members ADD COLUMN IF NOT EXISTS role           TEXT NOT NULL DEFAULT 'user';
-- ALTER TABLE members ADD COLUMN IF NOT EXISTS status         TEXT NOT NULL DEFAULT 'active';
-- ALTER TABLE members ADD COLUMN IF NOT EXISTS must_change_pw BOOLEAN NOT NULL DEFAULT false;

-- GAS에서 마이그레이션한 기존 멤버 활성화 (status 컬럼 추가 후 실행)
-- UPDATE members SET status = 'active' WHERE status = 'pending';
-- 첫 번째 멤버를 관리자로 설정 (id 값 확인 후 수정)
-- UPDATE members SET role = 'admin' WHERE id = 1;

-- 2. 적군 테이블
CREATE TABLE IF NOT EXISTS enemies (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    deck TEXT NOT NULL DEFAULT ''
);

-- 3. 공략 테이블
CREATE TABLE IF NOT EXISTS strategies (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target    TEXT NOT NULL,
    attack    TEXT NOT NULL DEFAULT '',
    pet       TEXT          DEFAULT '',
    formation TEXT          DEFAULT '기본',
    items     TEXT          DEFAULT '',
    note      TEXT          DEFAULT '',
    author    TEXT          DEFAULT '',
    created_at TIMESTAMPTZ  DEFAULT NOW()
);

-- 4. 전투기록 테이블
CREATE TABLE IF NOT EXISTS battle_records (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    nickname   TEXT NOT NULL,
    enemy_name TEXT         DEFAULT '',
    enemy_deck TEXT         DEFAULT '',
    my_deck    TEXT         DEFAULT '',
    pet        TEXT         DEFAULT '',
    formation  TEXT         DEFAULT '',
    result     TEXT         DEFAULT ''
);

-- 5. 공성전 테이블 (닉네임+요일 조합 UPSERT)
CREATE TABLE IF NOT EXISTS siege (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname  TEXT NOT NULL,
    day       TEXT NOT NULL,
    deck      TEXT DEFAULT '',
    pet       TEXT DEFAULT '',
    formation TEXT DEFAULT '기본',
    memo      TEXT DEFAULT '',
    pipeline  TEXT DEFAULT '',
    UNIQUE (nickname, day)
);

-- 6. 강림원정대 테이블 (닉네임+보스 조합 UPSERT)
--    보스 종류: 태오, 카일, 연희, 카르마, 파괴신
CREATE TABLE IF NOT EXISTS advent (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname        TEXT NOT NULL,
    boss            TEXT NOT NULL,
    team1_deck      TEXT DEFAULT '',
    team1_pet       TEXT DEFAULT '',
    team1_formation TEXT DEFAULT '기본',
    team1_memo      TEXT DEFAULT '',
    team1_pipeline  TEXT DEFAULT '',
    team2_deck      TEXT DEFAULT '',
    team2_pet       TEXT DEFAULT '',
    team2_formation TEXT DEFAULT '기본',
    team2_memo      TEXT DEFAULT '',
    team2_pipeline  TEXT DEFAULT '',
    cleared         TEXT DEFAULT 'false',
    UNIQUE (nickname, boss)
);

-- ============================================================
--  RLS (Row Level Security) — 기본값: 비활성화
--  현재 앱은 anon key로 전체 읽기/쓰기를 허용합니다.
--  보안이 필요한 경우 아래 주석을 해제하고 정책을 추가하세요.
-- ============================================================

-- ALTER TABLE members    ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE enemies    ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE strategies ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE battle_records ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE siege      ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE advent     ENABLE ROW LEVEL SECURITY;
